# Site settings
title: Tuningfork
email: contact@tuningfork.fr
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:
facebook_username: contact.tuningfork

# Build settings
markdown: kramdown
